networks:
  backend_network: 
    internal: true
  frontend_network:
    driver: bridge

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker-librairie
    volumes:
        - db_data:/var/lib/mysql
        - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
        - backend_network
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
        interval: 5s
  api:
    build: ./node-api
    expose:
        - "3000" 
    depends_on:
        db:
            condition: service_healthy
    networks:
        - backend_network
        - frontend_network
  frontend:
    build: ./frontend
    ports:
        - "8080:80" 
    depends_on:
      - api
    networks:
        - frontend_network
volumes:
    db_data: